Test matrix queue fix
fractalnetworksco/taskiq-matrix pull request #26
Opened 2024-01-17 22:38 UTC by lealjd

Full coverage for taskiq-matrix. Bug fixes, optimizations, and test adjustments.

2024-01-18 18:36 UTC, justin-russell requested changes

2024-01-18 18:36 UTC, justin-russell commented on taskiq_matrix/filters.py
> +    print('end=====', res.end)
Extra print statements

2024-01-18 18:36 UTC, justin-russell commented on taskiq_matrix/matrix_queue.py
> +        print('checkpoint next batch===========', self.checkpoint.since_token)
Extra print statements

2024-01-18 18:36 UTC, justin-russell commented on taskiq_matrix/matrix_queue.py
> +            print('here')
Extra print statements

2024-01-18 18:36 UTC, justin-russell commented on tests/queue/test_matrix_queue.py
>      print('lenth of list======', len(result))
Extra print statement

2024-01-18 18:37 UTC, justin-russell commented
Also, go ahead and bump up the version in `pyproject.toml` as well!

2024-01-19 15:27 UTC, lealjd commented
Got it all fixed up!

2024-01-19 15:37 UTC, justin-russell approved these changes

2024-01-19 15:38 UTC, merged